using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
using Gungeon;
using Dungeonator;
using System.Reflection;
using Alexandria.ItemAPI;
using System.Collections;
using System.Globalization;

namespace Alexandria.cAPI
{
    /// <summary>Cached and precomputed hat information</summary>
    public static class Hatabase
    {
        /// <summary>Helper class for storing additional hat offsets for individual sprite definitions</summary>
        public class FrameOffset
        {
            public Vector2 offset;
            public Vector2 flipOffset;
            public FrameOffset(float x, float y)
            {
                offset     = new Vector2( x / 16f, y / 16f);
                flipOffset = new Vector2(-x / 16f, y / 16f);
            }
        }

        // Currently-known hats that have been set up
        public static readonly Dictionary<string, Hat> Hats = new();

        // The last known hat each character was wearing
        public static readonly Dictionary<string, string> StoredHats = new();

        // Default offsets for unknown / custom characters
        public static readonly float defaultHeadLevelOffset = -14f/16f;
        public static readonly float defaultEyeLevelOffset  = -19f/16f;

        // Vertical offsets for where head-top hats should be placed on different characters (using character name)
        public static readonly Dictionary<string, float> CharacterNameHatHeadLevel = new Dictionary<string, float>()
        {
            {"PlayerRogue(Clone)",       - 6f/16f},
            {"PlayerMarine(Clone)",      -11f/16f},
            {"PlayerGuide(Clone)",       -14f/16f},
            {"PlayerConvict(Clone)",     -11f/16f},
            {"PlayerRobot(Clone)",         0f/16f},
            {"PlayerBullet(Clone)",      - 5f/16f},
            {"PlayerGunslinger(Clone)",    0f/16f},
            {"PlayerCoopCultist(Clone)", - 9f/16f},
        };

        // Vertical offsets for where eye-level hats should be placed on different characters (using character name)
        public static readonly Dictionary<string, float> CharacterNameEyeLevel = new Dictionary<string, float>()
        {
            {"PlayerRogue(Clone)",       -10f/16f},
            {"PlayerMarine(Clone)",      -14f/16f},
            {"PlayerGuide(Clone)",       -18f/16f},
            {"PlayerConvict(Clone)",     -15f/16f},
            {"PlayerRobot(Clone)",       - 5f/16f},
            {"PlayerBullet(Clone)",      -16f/16f},
            {"PlayerGunslinger(Clone)",   -6f/16f},
            {"PlayerCoopCultist(Clone)", -12f/16f},
        };

        // Animation frame-specific offsets for head-top hats
        public static readonly Dictionary<string, FrameOffset> HeadFrameOffsets = new()
        {
            {"convict_idle_002",                     new FrameOffset( 0, -1)},
            {"convict_idle_front_002",               new FrameOffset( 0, -1)},
            {"convict_idle_back_002",                new FrameOffset( 0, -1)},
            {"convict_idle_bw_002",                  new FrameOffset( 0, -1)},
            {"convict_idle_003",                     new FrameOffset( 0, -1)},
            {"convict_idle_front_003",               new FrameOffset( 0, -1)},
            {"convict_idle_back_003",                new FrameOffset( 0, -1)},
            {"convict_idle_bw_003",                  new FrameOffset( 0, -1)},
            {"convict_run_forward_001",              new FrameOffset( 0, -1)},
            {"convict_run_forward_002",              new FrameOffset( 0,  2)},
            {"convict_run_forward_004",              new FrameOffset( 0, -1)},
            {"convict_run_forward_005",              new FrameOffset( 0,  2)},
            {"convict_run_backwards_001",            new FrameOffset( 0, -1)},
            {"convict_run_backwards_002",            new FrameOffset( 0,  2)},
            {"convict_run_backwards_004",            new FrameOffset( 0, -1)},
            {"convict_run_backwards_005",            new FrameOffset( 0,  2)},
            {"convict_run_north_001",                new FrameOffset( 0,  0)},
            {"convict_run_north_002",                new FrameOffset( 0,  3)},
            {"convict_run_north_003",                new FrameOffset( 0,  2)},
            {"convict_run_north_004",                new FrameOffset( 0,  0)},
            {"convict_run_north_005",                new FrameOffset( 0,  3)},
            {"convict_run_north_006",                new FrameOffset( 0,  2)},
            {"convict_run_south_001",                new FrameOffset( 0,  0)},
            {"convict_run_south_002",                new FrameOffset( 0,  4)},
            {"convict_run_south_003",                new FrameOffset( 0,  2)},
            {"convict_run_south_004",                new FrameOffset( 0,  0)},
            {"convict_run_south_005",                new FrameOffset( 0,  4)},
            {"convict_run_south_006",                new FrameOffset( 0,  2)},
            {"guide_idle_right_front_002",           new FrameOffset( 0, -1)},
            {"guide_idle_right_front_003",           new FrameOffset( 0, -1)},
            {"guide_idle_front_002",                 new FrameOffset( 0, -1)},
            {"guide_idle_front_003",                 new FrameOffset( 0, -1)},
            {"guide_idle_back_002",                  new FrameOffset( 0, -1)},
            {"guide_idle_back_003",                  new FrameOffset( 0, -1)},
            {"guide_idle_back_right_002",            new FrameOffset( 0, -1)},
            {"guide_idle_back_right_003",            new FrameOffset( 0, -1)},
            {"guide_run_right_front_001",            new FrameOffset( 0,  2)},
            {"guide_run_right_front_002",            new FrameOffset( 0,  1)},
            {"guide_run_right_front_003",            new FrameOffset( 0, -1)},
            {"guide_run_right_front_004",            new FrameOffset( 0,  2)},
            {"guide_run_right_front_006",            new FrameOffset( 0, -1)},
            {"guide_run_back_right_001",             new FrameOffset( 0,  2)},
            {"guide_run_back_right_002",             new FrameOffset( 0,  1)},
            {"guide_run_back_right_003",             new FrameOffset( 0, -1)},
            {"guide_run_back_right_004",             new FrameOffset( 0,  2)},
            {"guide_run_back_right_006",             new FrameOffset( 0, -1)},
            {"guide_run_front_001",                  new FrameOffset( 0,  2)},
            {"guide_run_front_003",                  new FrameOffset( 0, -2)},
            {"guide_run_front_004",                  new FrameOffset( 0,  2)},
            {"guide_run_front_006",                  new FrameOffset( 0, -2)},
            {"guide_run_back_001",                   new FrameOffset( 0,  2)},
            {"guide_run_back_003",                   new FrameOffset( 0, -2)},
            {"guide_run_back_004",                   new FrameOffset( 0,  2)},
            {"guide_run_back_006",                   new FrameOffset( 0, -2)},
            {"marine_idle_front_right_002",          new FrameOffset( 0, -1)},
            {"marine_idle_front_right_003",          new FrameOffset( 0, -2)},
            {"marine_idle_front_right_004",          new FrameOffset( 0, -1)},
            {"marine_idle_back_right_002",           new FrameOffset( 0, -1)},
            {"marine_idle_back_right_003",           new FrameOffset( 0, -2)},
            {"marine_idle_back_right_004",           new FrameOffset( 0, -1)},
            {"marine_idle_back_002",                 new FrameOffset( 0, -1)},
            {"marine_idle_back_003",                 new FrameOffset( 0, -3)},
            {"marine_idle_back_004",                 new FrameOffset( 0, -2)},
            {"marine_idle_front_002",                new FrameOffset( 0, -1)},
            {"marine_idle_front_003",                new FrameOffset( 0, -3)},
            {"marine_idle_front_004",                new FrameOffset( 0, -2)},
            {"marine_run_front_right_001",           new FrameOffset( 0,  2)},
            {"marine_run_front_right_002",           new FrameOffset( 0,  1)},
            {"marine_run_front_right_003",           new FrameOffset( 0, -2)},
            {"marine_run_front_right_004",           new FrameOffset( 0,  2)},
            {"marine_run_front_right_005",           new FrameOffset( 0,  1)},
            {"marine_run_front_right_006",           new FrameOffset( 0, -2)},
            {"marine_run_back_right_001",            new FrameOffset( 0,  2)},
            {"marine_run_back_right_002",            new FrameOffset( 0,  1)},
            {"marine_run_back_right_003",            new FrameOffset( 0, -2)},
            {"marine_run_back_right_004",            new FrameOffset( 0,  2)},
            {"marine_run_back_right_005",            new FrameOffset( 0,  1)},
            {"marine_run_back_right_006",            new FrameOffset( 0, -2)},
            {"marine_run_front_001",                 new FrameOffset( 0,  1)},
            {"marine_run_front_002",                 new FrameOffset( 0,  0)},
            {"marine_run_front_003",                 new FrameOffset( 0, -2)},
            {"marine_run_front_004",                 new FrameOffset( 0,  1)},
            {"marine_run_front_005",                 new FrameOffset( 0,  0)},
            {"marine_run_front_006",                 new FrameOffset( 0, -2)},
            {"marine_run_back_001",                  new FrameOffset( 0,  2)},
            {"marine_run_back_002",                  new FrameOffset( 0,  1)},
            {"marine_run_back_003",                  new FrameOffset( 0, -1)},
            {"marine_run_back_004",                  new FrameOffset( 0,  2)},
            {"marine_run_back_005",                  new FrameOffset( 0,  1)},
            {"marine_run_back_006",                  new FrameOffset( 0, -1)},
            {"rogue_idle_001",                       new FrameOffset( 1,  0)},
            {"rogue_idle_002",                       new FrameOffset( 1, -1)},
            {"rogue_idle_003",                       new FrameOffset( 1, -1)},
            {"rogue_idle_004",                       new FrameOffset( 1,  0)},
            {"rogue_idle_backwards_001",             new FrameOffset( 1,  0)},
            {"rogue_idle_backwards_002",             new FrameOffset( 1, -1)},
            {"rogue_idle_backwards_003",             new FrameOffset( 1, -1)},
            {"rogue_idle_backwards_004",             new FrameOffset( 1,  0)},
            {"rogue_idle_back_002",                  new FrameOffset( 0, -1)},
            {"rogue_idle_back_003",                  new FrameOffset( 0, -1)},
            {"rogue_idle_front_002",                 new FrameOffset( 0, -2)},
            {"rogue_idle_front_003",                 new FrameOffset( 0, -2)},
            {"rogue_idle_front_004",                 new FrameOffset( 0, -1)},
            {"rogue_run_forward_001",                new FrameOffset( 0, -1)},
            {"rogue_run_forward_002",                new FrameOffset(-1,  1)},
            {"rogue_run_forward_003",                new FrameOffset(-1,  0)},
            {"rogue_run_forward_004",                new FrameOffset( 0, -1)},
            {"rogue_run_forward_005",                new FrameOffset( 1,  2)},
            {"rogue_run_forward_006",                new FrameOffset( 1,  0)},
            {"rogue_run_backward_001",               new FrameOffset( 0, -1)},
            {"rogue_run_backward_002",               new FrameOffset( 0,  2)},
            {"rogue_run_backward_003",               new FrameOffset( 0,  0)},
            {"rogue_run_backward_004",               new FrameOffset( 0, -1)},
            {"rogue_run_backward_005",               new FrameOffset( 0,  3)},
            {"rogue_run_backward_006",               new FrameOffset( 0,  0)},
            {"rogue_run_front_001",                  new FrameOffset( 1,  3)},
            {"rogue_run_front_002",                  new FrameOffset( 1,  2)},
            {"rogue_run_front_003",                  new FrameOffset( 0, -1)},
            {"rogue_run_front_004",                  new FrameOffset( 0,  2)},
            {"rogue_run_front_005",                  new FrameOffset( 0,  1)},
            {"rogue_run_front_006",                  new FrameOffset( 0,  0)},
            {"rogue_run_back_001",                   new FrameOffset( 0,  3)},
            {"rogue_run_back_002",                   new FrameOffset( 0,  2)},
            {"rogue_run_back_003",                   new FrameOffset( 0, -1)},
            {"rogue_run_back_004",                   new FrameOffset( 0,  2)},
            {"rogue_run_back_005",                   new FrameOffset( 0,  1)},
            {"rogue_run_back_006",                   new FrameOffset( 0,  0)},
            {"robot_idle_001",                       new FrameOffset( 1,  0)},
            {"robot_idle_002",                       new FrameOffset( 1,  0)},
            {"robot_idle_003",                       new FrameOffset( 1,  0)},
            {"robot_idle_004",                       new FrameOffset( 1,  0)},
            {"robot_idle_front_001",                 new FrameOffset( 0, -2)},
            {"robot_idle_front_002",                 new FrameOffset( 0,  0)},
            {"robot_idle_front_003",                 new FrameOffset( 0, -2)},
            {"robot_idle_front_004",                 new FrameOffset( 0, -3)},
            {"robot_run_front_001",                  new FrameOffset( 0,  0)},
            {"robot_run_front_002",                  new FrameOffset( 0, -2)},
            {"robot_run_front_003",                  new FrameOffset( 0, -2)},
            {"robot_run_front_004",                  new FrameOffset( 0,  0)},
            {"robot_run_front_005",                  new FrameOffset( 0, -2)},
            {"robot_run_front_006",                  new FrameOffset( 0, -2)},
            {"cultist_idle_front_right_003",         new FrameOffset( 0, -1)},
            {"cultist_idle_front_right_004",         new FrameOffset( 0, -1)},
            {"cultist_idle_back_right_003",          new FrameOffset( 0, -1)},
            {"cultist_idle_back_right_004",          new FrameOffset( 0, -1)},
            {"cultist_idle_front_003",               new FrameOffset( 0, -1)},
            {"cultist_idle_front_004",               new FrameOffset( 0, -1)},
            {"cultist_idle_back_003",                new FrameOffset( 0, -1)},
            {"cultist_idle_back_004",                new FrameOffset( 0, -1)},
            {"cultist_move_front_right_001",         new FrameOffset( 0,  2)},
            {"cultist_move_front_right_002",         new FrameOffset( 0,  1)},
            {"cultist_move_front_right_003",         new FrameOffset( 0,  0)},
            {"cultist_move_front_right_004",         new FrameOffset( 0,  1)},
            {"cultist_move_front_right_005",         new FrameOffset( 0,  0)},
            {"cultist_move_front_right_006",         new FrameOffset( 0,  0)},
            {"cultist_move_back_right_001",          new FrameOffset( 0,  2)},
            {"cultist_move_back_right_002",          new FrameOffset( 0,  1)},
            {"cultist_move_back_right_003",          new FrameOffset( 0,  0)},
            {"cultist_move_back_right_004",          new FrameOffset( 0,  1)},
            {"cultist_move_back_right_005",          new FrameOffset( 0,  0)},
            {"cultist_move_back_right_006",          new FrameOffset( 0,  0)},
            {"cultist_move_front_001",               new FrameOffset( 0,  2)},
            {"cultist_move_front_002",               new FrameOffset( 0,  0)},
            {"cultist_move_front_003",               new FrameOffset( 0, -3)},
            {"cultist_move_front_004",               new FrameOffset( 0,  1)},
            {"cultist_move_front_005",               new FrameOffset( 0, -1)},
            {"cultist_move_front_006",               new FrameOffset( 0, -2)},
            {"cultist_move_back_001",                new FrameOffset( 0,  2)},
            {"cultist_move_back_002",                new FrameOffset( 0,  0)},
            {"cultist_move_back_003",                new FrameOffset( 0, -3)},
            {"cultist_move_back_004",                new FrameOffset( 0,  1)},
            {"cultist_move_back_005",                new FrameOffset( 0, -1)},
            {"cultist_move_back_006",                new FrameOffset( 0, -2)},
            {"bullet_player_move_front_right_001",   new FrameOffset( 0,  1)},
            {"bullet_player_move_front_right_002",   new FrameOffset( 4,  1)},
            {"bullet_player_move_front_right_003",   new FrameOffset( 4,  0)},
            {"bullet_player_move_front_right_004",   new FrameOffset( 0,  1)},
            {"bullet_player_move_front_right_005",   new FrameOffset(-2,  1)},
            {"bullet_player_move_front_right_006",   new FrameOffset(-2,  1)},
            {"bullet_player_move_front_001",         new FrameOffset( 0,  1)},
            {"bullet_player_move_front_002",         new FrameOffset( 1,  1)},
            {"bullet_player_move_front_003",         new FrameOffset( 1,  1)},
            {"bullet_player_move_front_004",         new FrameOffset( 0,  1)},
            {"bullet_player_move_front_005",         new FrameOffset(-2,  1)},
            {"bullet_player_move_front_006",         new FrameOffset(-1,  1)},
            {"bullet_player_move_back_right_001",    new FrameOffset( 0,  1)},
            {"bullet_player_move_back_right_002",    new FrameOffset( 4,  1)},
            {"bullet_player_move_back_right_003",    new FrameOffset( 4,  0)},
            {"bullet_player_move_back_right_004",    new FrameOffset( 0,  1)},
            {"bullet_player_move_back_right_005",    new FrameOffset(-2,  1)},
            {"bullet_player_move_back_right_006",    new FrameOffset(-2,  1)},
            {"bullet_player_move_back_001",          new FrameOffset( 0,  1)},
            {"bullet_player_move_back_002",          new FrameOffset( 1,  1)},
            {"bullet_player_move_back_003",          new FrameOffset( 1,  1)},
            {"bullet_player_move_back_004",          new FrameOffset( 0,  1)},
            {"bullet_player_move_back_005",          new FrameOffset(-2,  1)},
            {"bullet_player_move_back_006",          new FrameOffset(-1,  1)},
        };

        // Animation frame-specific offsets for eye-level hats
        public static readonly Dictionary<string, FrameOffset> EyeFrameOffsets = new()
        {
            {"convict_idle_002",                     new FrameOffset( 0, -1)},
            {"convict_idle_front_002",               new FrameOffset( 0, -1)},
            {"convict_idle_back_002",                new FrameOffset( 0, -1)},
            {"convict_idle_bw_002",                  new FrameOffset( 0, -1)},
            {"convict_idle_003",                     new FrameOffset( 0, -1)},
            {"convict_idle_front_003",               new FrameOffset( 0, -1)},
            {"convict_idle_back_003",                new FrameOffset( 0, -1)},
            {"convict_idle_bw_003",                  new FrameOffset( 0, -1)},
            {"convict_run_forward_001",              new FrameOffset( 0, -1)},
            {"convict_run_forward_002",              new FrameOffset( 0,  2)},
            {"convict_run_forward_003",              new FrameOffset( 0,  0)},
            {"convict_run_forward_004",              new FrameOffset( 0, -1)},
            {"convict_run_forward_005",              new FrameOffset( 0,  3)},
            {"convict_run_forward_006",              new FrameOffset( 0, -1)},
            {"convict_run_backwards_001",            new FrameOffset( 0, -1)},
            {"convict_run_backwards_002",            new FrameOffset( 0,  2)},
            {"convict_run_backwards_003",            new FrameOffset( 0,  0)},
            {"convict_run_backwards_004",            new FrameOffset( 0, -1)},
            {"convict_run_backwards_005",            new FrameOffset( 0,  3)},
            {"convict_run_backwards_006",            new FrameOffset( 0, -1)},
            {"convict_run_north_001",                new FrameOffset( 0,  3)},
            {"convict_run_north_002",                new FrameOffset( 0,  1)},
            {"convict_run_north_003",                new FrameOffset( 0, -1)},
            {"convict_run_north_004",                new FrameOffset( 0,  4)},
            {"convict_run_north_005",                new FrameOffset( 0,  1)},
            {"convict_run_north_006",                new FrameOffset( 0, -1)},
            {"convict_run_south_001",                new FrameOffset( 0,  3)},
            {"convict_run_south_002",                new FrameOffset( 0,  1)},
            {"convict_run_south_003",                new FrameOffset( 0, -1)},
            {"convict_run_south_004",                new FrameOffset( 0,  4)},
            {"convict_run_south_005",                new FrameOffset( 0,  1)},
            {"convict_run_south_006",                new FrameOffset( 0, -1)},
            {"guide_idle_right_front_002",           new FrameOffset( 0, -1)},
            {"guide_idle_right_front_003",           new FrameOffset( 0, -1)},
            {"guide_idle_front_002",                 new FrameOffset( 0, -1)},
            {"guide_idle_front_003",                 new FrameOffset( 0, -1)},
            {"guide_idle_back_002",                  new FrameOffset( 0, -1)},
            {"guide_idle_back_003",                  new FrameOffset( 0, -1)},
            {"guide_idle_back_right_002",            new FrameOffset( 0, -1)},
            {"guide_idle_back_right_003",            new FrameOffset( 0, -1)},
            {"guide_run_right_front_001",            new FrameOffset( 0,  2)},
            {"guide_run_right_front_002",            new FrameOffset( 0,  1)},
            {"guide_run_right_front_003",            new FrameOffset( 0, -1)},
            {"guide_run_right_front_004",            new FrameOffset( 0,  2)},
            {"guide_run_right_front_006",            new FrameOffset( 0, -1)},
            {"guide_run_back_right_001",             new FrameOffset( 0,  2)},
            {"guide_run_back_right_002",             new FrameOffset( 0,  1)},
            {"guide_run_back_right_003",             new FrameOffset( 0, -1)},
            {"guide_run_back_right_004",             new FrameOffset( 0,  2)},
            {"guide_run_back_right_006",             new FrameOffset( 0, -1)},
            {"guide_run_front_001",                  new FrameOffset( 0,  2)},
            {"guide_run_front_003",                  new FrameOffset( 0, -2)},
            {"guide_run_front_004",                  new FrameOffset( 0,  2)},
            {"guide_run_front_006",                  new FrameOffset( 0, -2)},
            {"guide_run_back_001",                   new FrameOffset( 0,  2)},
            {"guide_run_back_003",                   new FrameOffset( 0, -2)},
            {"guide_run_back_004",                   new FrameOffset( 0,  2)},
            {"guide_run_back_006",                   new FrameOffset( 0, -2)},
            {"marine_idle_front_right_002",          new FrameOffset( 0, -1)},
            {"marine_idle_front_right_003",          new FrameOffset( 0, -2)},
            {"marine_idle_front_right_004",          new FrameOffset( 0, -1)},
            {"marine_idle_back_right_002",           new FrameOffset( 0, -1)},
            {"marine_idle_back_right_003",           new FrameOffset( 0, -2)},
            {"marine_idle_back_right_004",           new FrameOffset( 0, -1)},
            {"marine_idle_back_002",                 new FrameOffset( 0, -1)},
            {"marine_idle_back_003",                 new FrameOffset( 0, -3)},
            {"marine_idle_back_004",                 new FrameOffset( 0, -2)},
            {"marine_idle_front_002",                new FrameOffset( 0, -1)},
            {"marine_idle_front_003",                new FrameOffset( 0, -3)},
            {"marine_idle_front_004",                new FrameOffset( 0, -2)},
            {"marine_run_front_right_001",           new FrameOffset( 0,  2)},
            {"marine_run_front_right_002",           new FrameOffset( 0,  1)},
            {"marine_run_front_right_003",           new FrameOffset( 0, -2)},
            {"marine_run_front_right_004",           new FrameOffset( 0,  2)},
            {"marine_run_front_right_005",           new FrameOffset( 0,  1)},
            {"marine_run_front_right_006",           new FrameOffset( 0, -2)},
            {"marine_run_back_right_001",            new FrameOffset( 0,  2)},
            {"marine_run_back_right_002",            new FrameOffset( 0,  1)},
            {"marine_run_back_right_003",            new FrameOffset( 0, -2)},
            {"marine_run_back_right_004",            new FrameOffset( 0,  2)},
            {"marine_run_back_right_005",            new FrameOffset( 0,  1)},
            {"marine_run_back_right_006",            new FrameOffset( 0, -2)},
            {"marine_run_front_001",                 new FrameOffset( 0,  2)},
            {"marine_run_front_002",                 new FrameOffset( 0,  1)},
            {"marine_run_front_003",                 new FrameOffset( 0, -1)},
            {"marine_run_front_004",                 new FrameOffset( 0,  2)},
            {"marine_run_front_005",                 new FrameOffset( 0,  1)},
            {"marine_run_front_006",                 new FrameOffset( 0, -1)},
            {"marine_run_back_001",                  new FrameOffset( 0,  2)},
            {"marine_run_back_002",                  new FrameOffset( 0,  1)},
            {"marine_run_back_003",                  new FrameOffset( 0, -1)},
            {"marine_run_back_004",                  new FrameOffset( 0,  2)},
            {"marine_run_back_005",                  new FrameOffset( 0,  1)},
            {"marine_run_back_006",                  new FrameOffset( 0, -1)},
            {"rogue_idle_001",                       new FrameOffset( 1,  0)},
            {"rogue_idle_002",                       new FrameOffset( 1, -1)},
            {"rogue_idle_003",                       new FrameOffset( 1, -1)},
            {"rogue_idle_004",                       new FrameOffset( 1,  0)},
            {"rogue_idle_backwards_001",             new FrameOffset( 1,  0)},
            {"rogue_idle_backwards_002",             new FrameOffset( 1, -1)},
            {"rogue_idle_backwards_003",             new FrameOffset( 1, -1)},
            {"rogue_idle_backwards_004",             new FrameOffset( 1,  0)},
            {"rogue_idle_back_002",                  new FrameOffset( 0, -1)},
            {"rogue_idle_back_003",                  new FrameOffset( 0, -1)},
            {"rogue_idle_front_001",                 new FrameOffset( 1,  0)},
            {"rogue_idle_front_002",                 new FrameOffset( 1, -2)},
            {"rogue_idle_front_003",                 new FrameOffset( 1, -2)},
            {"rogue_idle_front_004",                 new FrameOffset( 1, -1)},
            {"rogue_idle_front_005",                 new FrameOffset( 1,  0)},
            {"rogue_idle_front_006",                 new FrameOffset( 1,  0)},
            {"rogue_run_forward_001",                new FrameOffset( 1, -1)},
            {"rogue_run_forward_002",                new FrameOffset( 0,  2)},
            {"rogue_run_forward_003",                new FrameOffset( 0,  0)},
            {"rogue_run_forward_004",                new FrameOffset( 1, -1)},
            {"rogue_run_forward_005",                new FrameOffset( 2,  3)},
            {"rogue_run_forward_006",                new FrameOffset( 2,  0)},
            {"rogue_run_backward_001",               new FrameOffset( 0, -1)},
            {"rogue_run_backward_002",               new FrameOffset( 0,  2)},
            {"rogue_run_backward_003",               new FrameOffset( 0,  0)},
            {"rogue_run_backward_004",               new FrameOffset( 0, -1)},
            {"rogue_run_backward_005",               new FrameOffset( 0,  3)},
            {"rogue_run_backward_006",               new FrameOffset( 0,  0)},
            {"rogue_run_front_001",                  new FrameOffset( 1,  2)},
            {"rogue_run_front_002",                  new FrameOffset( 1,  1)},
            {"rogue_run_front_003",                  new FrameOffset( 0, -1)},
            {"rogue_run_front_004",                  new FrameOffset( 1,  3)},
            {"rogue_run_front_005",                  new FrameOffset( 1,  2)},
            {"rogue_run_front_006",                  new FrameOffset( 0, -1)},
            {"rogue_run_back_001",                   new FrameOffset( 0,  3)},
            {"rogue_run_back_002",                   new FrameOffset( 0,  2)},
            {"rogue_run_back_003",                   new FrameOffset( 0, -1)},
            {"rogue_run_back_004",                   new FrameOffset( 0,  2)},
            {"rogue_run_back_005",                   new FrameOffset( 0,  1)},
            {"rogue_run_back_006",                   new FrameOffset( 0,  0)},
            {"robot_idle_001",                       new FrameOffset( 1,  0)},
            {"robot_idle_002",                       new FrameOffset( 1,  0)},
            {"robot_idle_003",                       new FrameOffset( 1,  0)},
            {"robot_idle_004",                       new FrameOffset( 1,  0)},
            {"robot_idle_front_001",                 new FrameOffset( 0, -1)},
            {"robot_idle_front_002",                 new FrameOffset( 0,  1)},
            {"robot_idle_front_003",                 new FrameOffset( 0, -1)},
            {"robot_idle_front_004",                 new FrameOffset( 0, -2)},
            {"robot_run_front_001",                  new FrameOffset( 0,  1)},
            {"robot_run_front_002",                  new FrameOffset( 0, -1)},
            {"robot_run_front_003",                  new FrameOffset( 0, -1)},
            {"robot_run_front_004",                  new FrameOffset( 0,  1)},
            {"robot_run_front_005",                  new FrameOffset( 0, -1)},
            {"robot_run_front_006",                  new FrameOffset( 0, -1)},
            {"cultist_idle_front_right_001",         new FrameOffset( 0,  0)},
            {"cultist_idle_front_right_002",         new FrameOffset( 0, -1)},
            {"cultist_idle_front_right_003",         new FrameOffset( 0, -2)},
            {"cultist_idle_front_right_004",         new FrameOffset( 0, -1)},
            {"cultist_idle_back_right_003",          new FrameOffset( 0, -1)},
            {"cultist_idle_back_right_004",          new FrameOffset( 0, -1)},
            {"cultist_idle_front_001",               new FrameOffset( 0,  0)},
            {"cultist_idle_front_002",               new FrameOffset( 0, -1)},
            {"cultist_idle_front_003",               new FrameOffset( 0, -1)},
            {"cultist_idle_front_004",               new FrameOffset( 0, -1)},
            {"cultist_idle_front_005",               new FrameOffset( 0,  0)},
            {"cultist_idle_front_006",               new FrameOffset( 0,  0)},
            {"cultist_idle_back_003",                new FrameOffset( 0, -1)},
            {"cultist_idle_back_004",                new FrameOffset( 0, -1)},
            {"cultist_move_front_right_001",         new FrameOffset( 1,  2)},
            {"cultist_move_front_right_002",         new FrameOffset( 1,  1)},
            {"cultist_move_front_right_003",         new FrameOffset( 0,  0)},
            {"cultist_move_front_right_004",         new FrameOffset( 0,  1)},
            {"cultist_move_front_right_005",         new FrameOffset( 0,  0)},
            {"cultist_move_front_right_006",         new FrameOffset( 0,  0)},
            {"cultist_move_back_right_001",          new FrameOffset( 0,  2)},
            {"cultist_move_back_right_002",          new FrameOffset( 0,  1)},
            {"cultist_move_back_right_003",          new FrameOffset( 0,  0)},
            {"cultist_move_back_right_004",          new FrameOffset( 0,  1)},
            {"cultist_move_back_right_005",          new FrameOffset( 0,  0)},
            {"cultist_move_back_right_006",          new FrameOffset( 0,  0)},
            {"cultist_move_front_001",               new FrameOffset( 2,  2)},
            {"cultist_move_front_002",               new FrameOffset( 2,  0)},
            {"cultist_move_front_003",               new FrameOffset( 0, -3)},
            {"cultist_move_front_004",               new FrameOffset(-2,  1)},
            {"cultist_move_front_005",               new FrameOffset(-2, -1)},
            {"cultist_move_front_006",               new FrameOffset( 0, -2)},
            {"cultist_move_back_001",                new FrameOffset( 0,  2)},
            {"cultist_move_back_002",                new FrameOffset( 0,  0)},
            {"cultist_move_back_003",                new FrameOffset( 0, -3)},
            {"cultist_move_back_004",                new FrameOffset( 0,  1)},
            {"cultist_move_back_005",                new FrameOffset( 0, -1)},
            {"cultist_move_back_006",                new FrameOffset( 0, -2)},
            {"bullet_player_move_front_right_001",   new FrameOffset( 0,  1)},
            {"bullet_player_move_front_right_002",   new FrameOffset( 1,  0)},
            {"bullet_player_move_front_right_003",   new FrameOffset( 1, -2)},
            {"bullet_player_move_front_right_004",   new FrameOffset( 0,  1)},
            {"bullet_player_move_front_right_005",   new FrameOffset( 0, -1)},
            {"bullet_player_move_front_right_006",   new FrameOffset( 0,  2)},
            {"bullet_player_move_front_001",         new FrameOffset( 0,  4)},
            {"bullet_player_move_front_002",         new FrameOffset( 1,  4)},
            {"bullet_player_move_front_003",         new FrameOffset( 1,  3)},
            {"bullet_player_move_front_004",         new FrameOffset( 0,  4)},
            {"bullet_player_move_front_005",         new FrameOffset(-2,  3)},
            {"bullet_player_move_front_006",         new FrameOffset(-1,  2)},
            {"bullet_player_move_back_right_001",    new FrameOffset( 0,  1)},
            {"bullet_player_move_back_right_002",    new FrameOffset( 4,  1)},
            {"bullet_player_move_back_right_003",    new FrameOffset( 4,  0)},
            {"bullet_player_move_back_right_004",    new FrameOffset( 0,  1)},
            {"bullet_player_move_back_right_005",    new FrameOffset(-2,  1)},
            {"bullet_player_move_back_right_006",    new FrameOffset(-2,  1)},
            {"bullet_player_move_back_001",          new FrameOffset( 0,  1)},
            {"bullet_player_move_back_002",          new FrameOffset( 1,  1)},
            {"bullet_player_move_back_003",          new FrameOffset( 1,  1)},
            {"bullet_player_move_back_004",          new FrameOffset( 0,  1)},
            {"bullet_player_move_back_005",          new FrameOffset(-2,  1)},
            {"bullet_player_move_back_006",          new FrameOffset(-1,  1)},
        };
    }
}
