#!/bin/bash
#Helper script for generating my gungeon mod's .csproj file

#Important top level variables
namespace="CwaffingTheGungy"      #namespace used throughout source code; need to change for my own mod eventually
projectname="CwaffingTheGungy"    #name of the DLL to create
projfile="./CwaffingItems.csproj" #the name of the csproj file to generate

#Easy colors (condensed)
  BLN="\e[0m"   ; UND="\e[1;4m" ; INV="\e[1;7m" ; CRT="\e[1;41m";
  BLK="\e[1;30m"; RED="\e[1;31m"; GRN="\e[1;32m"; YLW="\e[1;33m";
  BLU="\e[1;34m"; MGN="\e[1;35m"; CYN="\e[1;36m"; WHT="\e[1;37m";

#Array of items to include in the base project file
includes=()

#Manually populated includes
includes+=('<None Include="packages.config" />')
# includes+=('<Reference Include="System" />')
# includes+=('<Folder Include="Characters\Acolyte\newspritesetup\custom\" />')
# includes+=('<Folder Include="Characters\Shade\newspritesetup\custom\" />')
# includes+=('<Reference Include="Ionic.Zip, Version=1.9.1.8"/>')

#Regenerate audio sources
echo -e "[${GRN}>${BLN}] Regenerating audio bank"
./genaudio
#Source files
echo -e "[${GRN}>${BLN}] Scanning for source files"
while read -r line; do
  includes+=("<Compile Include=\"${line}\" />")
done <<< $(find "src" -type f -not -path "src/StandardAPI/ItemAPI/Examples/*" -not -path "src/StandardAPI/ItemAPI/FakePrefab/*" -not -path "src/SpriteBuilder.cs" | sed -r 's@/@\\@g')

#Custom Character Embedded resources
echo -e "[${GRN}>${BLN}] Scanning for custom characters"
while read -r line; do
  includes+=("<EmbeddedResource Include=\"${line}\" />")
done <<< $(find "Characters" -type f | sed -r 's@/@\\@g')

#Normal Embedded resources
echo -e "[${GRN}>${BLN}] Scanning for resources"
while read -r line; do
  includes+=("<EmbeddedResource Include=\"${line}\" />")
done <<< $(find "Resources" -type f | sed -r 's@/@\\@g')

#Unversioned EtG Unity Packages (skipping version numbers because there's no way to tell just by looking and it was causing problems)
echo -e "[${GRN}>${BLN}] Scanning for EtG DLLs"
while read -r line; do
  includes+=("<Reference Include=\"$(echo "$line" | rev | cut -f 1 -d '\' | cut -f 2- -d '.' | rev)\"/>")
done <<< $(find "packages/EtG.UnityEngine.1.0.0" -path "*.dll" | sed -r 's@/@\\@g')

#Versioned packages, net35
echo -e "[${GRN}>${BLN}] Scanning for net35 DLLs"
while read -r line; do
  includes+=("<Reference Include=\"$(echo "$line" | rev | cut -f 1 -d '\' | cut -f 2- -d '.' | rev)\"/>")
done <<< $(find "packages" -path "*net35*.dll" | sed -r 's@/@\\@g')

#Generate the template .csproj file
echo -e "[${GRN}>${BLN}] Generating .csproj template"
template=`cat <<'HERE'
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{52A82040-5BED-4ACB-9894-41A595F284CB}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>%s</RootNamespace>
    <AssemblyName>%s</AssemblyName>
    <TargetFrameworkVersion>v3.5</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    %s
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project=".\packages\BepInEx.Core.5.4.21\build\BepInEx.Core.targets" Condition="Exists('.\packages\BepInEx.Core.5.4.21\build\BepInEx.Core.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('.\packages\BepInEx.Core.5.4.21\build\BepInEx.Core.targets')" Text="$([System.String]::Format('$(ErrorText)', '.\packages\BepInEx.Core.5.4.21\build\BepInEx.Core.targets'))" />
  </Target>
</Project>
HERE`

#Escape all of the backslashes for printf
template="$(echo "$template" | sed -r 's@\\@\\\\@g')"
#Generate our substitution from our includes array
replace="$(printf "%s\n" "${includes[@]}")"

echo -e "[${GRN}>${BLN}] Substituting .csproj template"
#Get old checksum of generated csproj file
oldchecksum="$(md5sum "$projfile" | cut -f 1 -d ' ')"
#Invoke the substitution and create our projects file
printf "$template" "$namespace" "$projectname" "$replace" | xmllint --format - > "${projfile}.new"
#Get new checksum of generated csproj file
newchecksum="$(md5sum "${projfile}.new" | cut -f 1 -d ' ')"

#Compare checksums and clobber the old .csproj file as necessary
if [ "$oldchecksum" == "$newchecksum" ]; then
  echo -e "[${GRN}>${BLN}]   No changes to .csproj file!"
  /bin/rm "${projfile}.new"
else
  echo -e "[${GRN}>${BLN}]   New .csproj file generated, rebuilding project"
  /bin/rm "${projfile}"
  /bin/cp "${projfile}.new" "${projfile}"
fi

#Don't warn about unused variables (semicolon delimited)
nowarn="CS0414"

#Finally rebuild the project
echo -e "[${GRN}>${BLN}] Building project"
msbuild -noLogo -warnAsMessage:"${nowarn}" -v:minimal -clp:"Summary;Verbosity=minimal"

if [ $? -gt 0 ]; then
  echo -e "[${RED}@${BLN}] Build failed! D: Check errors above"
else
  echo -e "[${GRN}>${BLN}] Build succeeded! :D"
  if [ $# -gt 0 ] && [ "$1" == "-g" ]; then
    ./importmod
    gungy-modded
  fi
fi

