#!/bin/bash
#Helper script for generating my gungeon mod's .csproj file

#Important top level variables
namespace="NevernamedsItems"      #namespace used throughout source code; need to change for my own mod eventually
projectname="CwaffingTheGungy"    #name of the DLL to create
projfile="./CwaffingItems.csproj" #the name of the csproj file to generate

#Array of items to include in the base project file
includes=()

#Manually populated includes
includes+=('<None Include="packages.config" />')
includes+=('<Reference Include="System" />')
includes+=('<Folder Include="Characters\Acolyte\newspritesetup\custom\" />')
includes+=('<Folder Include="Characters\Shade\newspritesetup\custom\" />')
includes+=('<Reference Include="Ionic.Zip, Version=1.9.1.8"/>')

#Source files
while read -r line; do
  includes+=("<Compile Include=\"${line}\" />")
done <<< $(find "src" -type f -not -path "src/StandardAPI/ItemAPI/Examples/*" -not -path "src/StandardAPI/ItemAPI/FakePrefab/*" -not -path "src/SpriteBuilder.cs" | sed -r 's@/@\\@g')

#Custom Character Embedded resources
while read -r line; do
  includes+=("<EmbeddedResource Include=\"${line}\" />")
done <<< $(find "Characters" -type f | sed -r 's@/@\\@g')

#Normal Embedded resources
while read -r line; do
  includes+=("<EmbeddedResource Include=\"${line}\" />")
done <<< $(find "Resources" -type f | sed -r 's@/@\\@g')

#Unversioned EtG Unity Packages (skipping version numbers because there's no way to tell just by looking and it was causing problems)
while read -r line; do
  includes+=("<Reference Include=\"$(echo "$line" | rev | cut -f 1 -d '\' | cut -f 2- -d '.' | rev)\"/>")
done <<< $(find "packages/EtG.UnityEngine.1.0.0" -type f -path "*.dll" | sed -r 's@/@\\@g')

#Versioned packages, net35
while read -r line; do
  includes+=("<Reference Include=\"$(echo "$line" | rev | cut -f 1 -d '\' | cut -f 2- -d '.' | rev)\"/>")
done <<< $(find "packages" -type f -path "*net35*.dll" | sed -r 's@/@\\@g')

#Generate the template .csproj file
template=`cat <<'HERE'
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{52A82040-5BED-4ACB-9894-41A595F284CB}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>%s</RootNamespace>
    <AssemblyName>%s</AssemblyName>
    <TargetFrameworkVersion>v3.5</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    %s
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project=".\packages\BepInEx.Core.5.4.21\build\BepInEx.Core.targets" Condition="Exists('.\packages\BepInEx.Core.5.4.21\build\BepInEx.Core.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('.\packages\BepInEx.Core.5.4.21\build\BepInEx.Core.targets')" Text="$([System.String]::Format('$(ErrorText)', '.\packages\BepInEx.Core.5.4.21\build\BepInEx.Core.targets'))" />
  </Target>
</Project>
HERE`

#Escape all of the backslashes for printf
template="$(echo "$template" | sed -r 's@\\@\\\\@g')"
#Generate our substitution from our includes array
replace="$(printf "%s\n" "${includes[@]}")"
#Invoke the substitution and create our projects file
printf "$template" "$namespace" "$projectname" "$replace" | xmllint --format - > "$projfile"

#Run msbuild for good measure
# msbuild
