#!/bin/bash
#Helper script for importing mod into the gungeons plugin folder

#Directory where Gungeon plugins go
plugindir="/xmedia/pretzel/Steam/steamapps/common/Enter the Gungeon/BepInEx/plugins/"
#Get our project name from the genproject script
projectname="$(cat "./genproject" | grep -m1 "projectname" | cut -f 2 -d '"')"    #name of the DLL to create
#DLL name is directly based on the project name
dllname="./bin/Debug/${projectname}.dll"
#Copy it over
cp "$dllname" "$plugindir"
echo "Done! :D"
